/*flexberryautogenerated="true"*/
namespace NewPlatform.SampleV3toV4
{
    using System;
    using ICSSoft.STORMNET.Web.Controls;

    using Resources;

    public partial class NotebookL : BaseListForm<Notebook>
    {
        /// <summary>
        /// Конструктор без параметров,
        /// инициализирует свойства, соответствующие конкретной форме.
        /// </summary>
        public NotebookL() : base(Notebook.Views.NotebookL)
        {
            EditPage = NotebookE.FormPath;
        }
                
        /// <summary>
        /// Путь до формы.
        /// </summary>
        public static string FormPath
        {
            get { return "~/forms/Notebook/NotebookL.aspx"; }
        }

        /// <summary>
        /// Вызывается самым первым в Page_Load.
        /// </summary>
        protected override void Preload()
        {
        }

        /// <summary>
        /// Вызывается самым последним в Page_Load.
        /// </summary>
        protected override void Postload()
        {
        }
    }
}
