//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.SampleV3toV4
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Hardware.
    /// </summary>
    // *** Start programmer edit section *** (Hardware CustomAttributes)

    // *** End programmer edit section *** (Hardware CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("HardwareE", new string[] {
            "Name as \'Name\'",
            "SerialNumber as \'Serial number\'"})]
    public class Hardware : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fSerialNumber;
        
        private NewPlatform.SampleV3toV4.Notebook fNotebook;
        
        // *** Start programmer edit section *** (Hardware CustomMembers)

        // *** End programmer edit section *** (Hardware CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Name CustomAttributes)

        // *** End programmer edit section *** (Hardware.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Name Get start)

                // *** End programmer edit section *** (Hardware.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Hardware.Name Get end)

                // *** End programmer edit section *** (Hardware.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Name Set start)

                // *** End programmer edit section *** (Hardware.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Hardware.Name Set end)

                // *** End programmer edit section *** (Hardware.Name Set end)
            }
        }
        
        /// <summary>
        /// SerialNumber.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.SerialNumber CustomAttributes)

        // *** End programmer edit section *** (Hardware.SerialNumber CustomAttributes)
        [StrLen(255)]
        public virtual string SerialNumber
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.SerialNumber Get start)

                // *** End programmer edit section *** (Hardware.SerialNumber Get start)
                string result = this.fSerialNumber;
                // *** Start programmer edit section *** (Hardware.SerialNumber Get end)

                // *** End programmer edit section *** (Hardware.SerialNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.SerialNumber Set start)

                // *** End programmer edit section *** (Hardware.SerialNumber Set start)
                this.fSerialNumber = value;
                // *** Start programmer edit section *** (Hardware.SerialNumber Set end)

                // *** End programmer edit section *** (Hardware.SerialNumber Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку NewPlatform.SampleV3toV4.Notebook.
        /// </summary>
        // *** Start programmer edit section *** (Hardware.Notebook CustomAttributes)

        // *** End programmer edit section *** (Hardware.Notebook CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Notebook"})]
        public virtual NewPlatform.SampleV3toV4.Notebook Notebook
        {
            get
            {
                // *** Start programmer edit section *** (Hardware.Notebook Get start)

                // *** End programmer edit section *** (Hardware.Notebook Get start)
                NewPlatform.SampleV3toV4.Notebook result = this.fNotebook;
                // *** Start programmer edit section *** (Hardware.Notebook Get end)

                // *** End programmer edit section *** (Hardware.Notebook Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Hardware.Notebook Set start)

                // *** End programmer edit section *** (Hardware.Notebook Set start)
                this.fNotebook = value;
                // *** Start programmer edit section *** (Hardware.Notebook Set end)

                // *** End programmer edit section *** (Hardware.Notebook Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "HardwareE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View HardwareE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("HardwareE", typeof(NewPlatform.SampleV3toV4.Hardware));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Hardware.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfHardware CustomAttributes)
    public class DetailArrayOfHardware : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (NewPlatform.SampleV3toV4.DetailArrayOfHardware members)

        // *** End programmer edit section *** (NewPlatform.SampleV3toV4.DetailArrayOfHardware members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Hardware by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Hardware.
        /// </summary>
        public DetailArrayOfHardware(NewPlatform.SampleV3toV4.Notebook fNotebook) : 
                base(typeof(Hardware), ((ICSSoft.STORMNET.DataObject)(fNotebook)))
        {
        }
        
        public NewPlatform.SampleV3toV4.Hardware this[int index]
        {
            get
            {
                return ((NewPlatform.SampleV3toV4.Hardware)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(NewPlatform.SampleV3toV4.Hardware dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
